### ISSUE TITLE
_csv.Error: field larger than field limit (131072)

### ISSUE THREAD

**Issue by largui** [princenyeche/jiraone#129]
Hello support
I got this issue:
<Response [200]>  ::downloading issues at page: 3 of 3
Processing. Current progress: 25%
Processing. Current progress: 50%
Processing. Current progress: 75%
Traceback (most recent call last):
  File "exportcsvfullxypoc_3.py", line 14, in <module>
    issue_export(jql=jql, extension="csv", fields=fields, final_file="/scripts/Python/backup"+d1, page=(0,3))
  File "/home/sleondelarosa/.local/lib/python3.8/site-packages/jiraone/reporting.py", line 4696, in export_issues
    merging_files()  # loop through each file and attempt combination
  File "/home/sleondelarosa/.local/lib/python3.8/site-packages/jiraone/reporting.py", line 4656, in merging_files
    file_reader(
  File "/home/sleondelarosa/.local/lib/python3.8/site-packages/jiraone/reporting.py", line 7932, in file_reader
    load = [d for d in read]
  File "/home/sleondelarosa/.local/lib/python3.8/site-packages/jiraone/reporting.py", line 7932, in <listcomp>
    load = [d for d in read]
_csv.Error: field larger than field limit (131072)

Is it possible to extend the field limit?
Version jiraone 0.8.2
Thanks and regards,
Sergio

**Comment by princenyeche** [comment]
Hey @largui 

A similar question was asked [here](https://github.com/princenyeche/jiraone/issues/127). I recommend following the same workaround to get the CSV field limit increased for your use case.

**Comment by largui** [comment]
Hey @princenyeche,
Thanks for your help. Now it is working.

Regards,
Sergio
