### ISSUE TITLE
An error has occurred: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by Grijak** [princenyeche/jiraone#141]
Hello,

I am currently trying to perform a JSON export with  jiraone.

Unfortunately I get the following message:

`Downloading issue export in JSON format.
<Response [200]> OK ::downloading issues at page: 0 of 0
Processing. Current progress: 100%
Converting Jira custom field names to Jira JSON compatible names.
Verifying users membership
Searching for user data.
Verifying Sprint values.
Extracting Sprint Ids from values.
Searching for Sprint data
JSON conversion started.
The default CSV separator is a comma for the delimit argument, no action taken.Traceback (most recent call last):
  File "C:\Users\dietz\AppData\Local\Programs\Python\Python312\Lib\site-packages\jiraone\reporting.py", line 7019, in json_field_builder
    field_builder(
  File "C:\Users\dietz\AppData\Local\Programs\Python\Python312\Lib\site-packages\jiraone\reporting.py", line 7012, in field_builder
    start_process()
  File "C:\Users\dietz\AppData\Local\Programs\Python\Python312\Lib\site-packages\jiraone\reporting.py", line 6629, in start_process
    if not obj_name.get("column_name").startswith(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
An error has occurred: 'NoneType' object has no attribute 'startswith'`

Probably a customfield is causing problems? To limit the problem, I have tried to export only certain custom fields. However, this does not seem to be possible for JSON.

Is there a possibility to restrict the customfields for the JSON export?

I get everything exported cleanly via CSV.

BR
Marcel

**Comment by princenyeche** [comment]
Hey @Grijak  this is the same problem reported here #122. It is a customfield issue but I've still not gotten the time to look properly into it. I'll keep you updated on this.

**Comment by princenyeche** [comment]
Hey @Grijak I've pushed a new version which could fix this issue. Try it out and let me know if it resolves this issue for you.

**Comment by princenyeche** [comment]
It seems the problem still exists, so I'll continue fixing it.
